services:
  ubuntu22:
    # image: xx  
    build:
      context: ../
      dockerfile: docker/Dockerfile
      # args:
      #   # you can set environment variables, otherwise default values will be used
      #   USER_NAME: ${HOST_USER_NAME:-gsplat}  # export HOST_USER_NAME=$USER
      #   GROUP_NAME: ${HOST_GROUP_NAME:-gsplats}
      #   UID: ${HOST_UID:-1000}  # export HOST_UID=$(id -u)
      #   GID: ${HOST_GID:-1000}  # export HOST_GID=$(id -g)
      shm_size: '40gb'
    shm_size: '40gb'
    environment:
      NVIDIA_DISABLE_REQUIRE: 1  # avoid wrong `nvidia-container-cli: requirement error`
    tty: true
    volumes:
        - ../:/root/code
        - /mnt/data/hzhu/:/root/data
    ports:
      - "10022:22" # ssh
      - "18888:8888" # jupyter
      - "16006:6006" # tensorboard
      - "16007:6007" # other viewers
      - "16008:6008" # other viewers
      - "16009:6009" # other viewers
      - "16010:6010" # other viewers
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]